// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn0TJkKfzb3gphiZ7NjAvA90kDoPMtR_o',
    appId: '1:650324673364:web:3d0e0cb6493174b6047ec1',
    messagingSenderId: '650324673364',
    projectId: 'lock-in-factory-f6a0f',
    authDomain: 'lock-in-factory-f6a0f.firebaseapp.com',
    storageBucket: 'lock-in-factory-f6a0f.firebasestorage.app',
    measurementId: 'G-K14N5H0ZK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH_mrDTMZSIuOAls3IownAlVqpmduMqQc',
    appId: '1:650324673364:android:86c33f4ab107e6cc047ec1',
    messagingSenderId: '650324673364',
    projectId: 'lock-in-factory-f6a0f',
    storageBucket: 'lock-in-factory-f6a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vy4wbtwOjQs_BnRvRJEiVmRXE-kBhbY',
    appId: '1:650324673364:ios:ad98eb5167baf77b047ec1',
    messagingSenderId: '650324673364',
    projectId: 'lock-in-factory-f6a0f',
    storageBucket: 'lock-in-factory-f6a0f.firebasestorage.app',
    iosClientId: '650324673364-os4ufquk8fcv19u68ilih2uhdg2kuqlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1vy4wbtwOjQs_BnRvRJEiVmRXE-kBhbY',
    appId: '1:650324673364:ios:ad98eb5167baf77b047ec1',
    messagingSenderId: '650324673364',
    projectId: 'lock-in-factory-f6a0f',
    storageBucket: 'lock-in-factory-f6a0f.firebasestorage.app',
    iosClientId: '650324673364-os4ufquk8fcv19u68ilih2uhdg2kuqlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn0TJkKfzb3gphiZ7NjAvA90kDoPMtR_o',
    appId: '1:650324673364:web:b8d7456a11a3accd047ec1',
    messagingSenderId: '650324673364',
    projectId: 'lock-in-factory-f6a0f',
    authDomain: 'lock-in-factory-f6a0f.firebaseapp.com',
    storageBucket: 'lock-in-factory-f6a0f.firebasestorage.app',
    measurementId: 'G-R10RNSGSSS',
  );

}